### ISSUE TITLE
How to open my savefile in Yokai Watch 3?

### ISSUE THREAD

**Issue by Kyline491** [Originyan/Yokai-Watch-3-Save-Editor#2]
If you're still there Originyan, can you show me the way on how will I open my savefile (.yw) in the game? I'm kind of clueless in opening it and continuing my game will make me appreciate it.

**Comment by Originyan** [comment]
You must have Checkpoint on the console, then extract the backup to the sd card. Then you need to download the save editor, run the .exe and open the .yw backup that was extracted from the console. After the modifications on the backup made, save the modified backup on the sd card of the console, then with Checkpoint apply the modified backup.

**Comment by Kyline491** [comment]
Thank you so much! I thought I lost my game forever. Big kiss from a geeky gal🤗
Keep saving lives from Yokai watch fans💛
